### PR TITLE
Add BIOS update file for Xiaomi air 12.5 1st gen

### PR DESCRIPTION
**Pull request by Koohoko**
CPU: m6Y30
Motherboard: T1612
Version: A09

### CODE REVIEW

**Comment by francescobabbaro** [comment]
Could be compatible with 2nd gen (7y30)? And which issues does it fix?

**Comment by Koohoko** [comment]
> Could be compatible with 2nd gen (7y30)? And which issues does it fix?

I dont think so, better check the motherboard specs beforehand, this bios fits the TIMI TM1612 one.
I think it mainly adressed some bugs on power management (fix sleep issues) comparing to my original A04 version.

**Comment by francescobabbaro** [comment]
> > Could be compatible with 2nd gen (7y30)? And which issues does it fix?
> 
> I dont think so, better check the motherboard specs beforehand, this bios fits the TIMI TM1612 one.
> I think it mainly adressed some bugs on power management (fix sleep issues) comparing to my original A04 version.

I agree. Which kind of power management bugs?

**Comment by Koohoko** [comment]
Before I updated (when I was using the A04 version), the hackintosh can not
wake up after sleep.

**Comment by francescobabbaro** [comment]
> Before I updated (when I was using the A04 version), the hackintosh can not wake up after sleep.
> […](#)

Understood. Thanks a lot.

**Comment by webfalter** [comment]
Is there an official source for the Bios version? Not that it's an 13 inch A09.

**Pull request merged**
